# Generated by Django 5.0.4 on 2024-04-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='img_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='img_url',
            field=models.TextField(),
        ),
    ]
