# Generated by Django 5.0.4 on 2024-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_song_playlist_song_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', to='api.playlist'),
        ),
    ]
